seed: 42
K_fold: 5
epoch: 50
image_size: 256
accelerator: "mps"
devices: 1
precision: "16"
pretrained: True
drop_rate: 0
learning_rate: 1e-3
weight_decay: 1e-5
step_size: 5
gamma: 0.5
batch_size: 64
num_workers: 4
data_root: "data"
transform: True
mean: [0.485, 0.456, 0.406]
std: [0.229, 0.224, 0.225]
