wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.8.16
    cli_version: 0.15.0
    framework: lightning
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1682472038.812021
    t:
      1:
      - 1
      - 5
      - 9
      - 41
      - 53
      - 55
      - 80
      2:
      - 1
      - 5
      - 9
      - 41
      - 53
      - 55
      - 80
      3:
      - 23
      4: 3.8.16
      5: 0.15.0
      8:
      - 4
      - 5
